language: python
python: "3.5"
dist: trusty
sudo: true
before_install:
  - sudo apt update && sudo apt install -y enchant
install:
  - pip install -U setuptools
  - pip install -U pyenchant sphinx-rtd-theme sphinxcontrib-spelling
script:
  - make spelling
  # show list of misspelled words
  - cat "_build/spelling/output.txt"
  - make html
  # fail the build in case of any misspelled words
  - if [[ -s "_build/spelling/output.txt" ]]; then false; fi
notifications:
  email: false
